// ============================================================
//  PIACHULIST — dane poziomów (plik generowany przez admin.html)
//  Kolejność w tablicy = miejsce na liście; numery liczą się same.
//  id: unikalny, nie zmieniaj go po dodaniu (po nim liczy się historia)
//  diff: easy | medium | hard | insane | extreme | unrated
//  link (opcjonalne): link do Twojego przejścia; hardest:true (opcjonalne)
// ============================================================
const LEVELS = [
  { id:"acu", name:"Acu", creator:"neigefeu", diff:"extreme", thumb:"thumbnails/acu.png", hardest:true },
  { id:"magic-life", name:"Magic Life", creator:"Astraa", diff:"insane", thumb:"https://i.ytimg.com/vi/G7AsIsPUvYM/maxresdefault.jpg", link:"https://www.youtube.com/watch?v=nWA6bq-ttH8&t=26s&ab_channel=%5BGD%5DP1achu" },
  { id:"windy-landscape", name:"Windy Landscape", creator:"WOOGI1411", diff:"insane", thumb:"https://i.ytimg.com/vi/hTX0Ch5bgMw/maxresdefault.jpg", link:"https://www.youtube.com/watch?v=nWA6bq-ttH8&t=26s&ab_channel=%5BGD%5DP1achu" },
  { id:"anya-ii", name:"Anya II", creator:"Anya21", diff:"hard", thumb:"https://i.ytimg.com/vi/-hab-9xJ4OY/maxresdefault.jpg" },
  { id:"shitty-acheron-buff", name:"Shitty Acheron Buff", creator:"p1achu", diff:"unrated", thumb:"thumbnails/acheron_buffed.png", link:"https://www.youtube.com/watch?v=9-7eWPJNNeY&ab_channel=%5BGD%5DP1achu" },
  { id:"crazy", name:"CraZy", creator:"DavJT", diff:"hard", thumb:"https://static.wikia.nocookie.net/geometry-dash-fan/images/c/cf/Maxresdefaultcrazylevel.jpg/revision/latest?cb=20220301022730" },
  { id:"azure", name:"Azure", creator:"eEddy", diff:"hard", thumb:"https://i.ytimg.com/vi/Vo9aGzciFxA/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLCKemj7gB6Ofe7RYYaAoHUrrPTGyw" },
  { id:"shitty-napalm", name:"Shitty Napalm", creator:"TrickGND", diff:"unrated", thumb:"thumbnails/napalm.png" },
  { id:"jawbreaker", name:"Jawbreaker", creator:"ZenthicAlpha", diff:"hard", thumb:"https://external-preview.redd.it/beat-jawbreaker-in-less-than-2-days-took-me-1374-attempts-v0-HIx1G9Kn6eFhW6D-i84Vs1nfGjcmQe-iGYRMKVhUMQI.png?format=pjpg&auto=webp&s=95f68778ffb832bd5c317e96c48749141ee88d09" },
  { id:"flatline", name:"Flatline", creator:"ZmLcherry", diff:"hard", thumb:"https://i.ytimg.com/vi/4uRxDenrrKI/maxresdefault.jpg" },
  { id:"sonic-wave-nerfed", name:"Sonic Wave Nerfed", creator:"p1achu", diff:"unrated", thumb:"thumbnails/sonic_wave.png" },
  { id:"shitty-rauchkammer", name:"Shitty Rauchkammer", creator:"ItsCasanova", diff:"unrated", thumb:"thumbnails/shitty_rauchkammer.png" },
  { id:"shitty-rust", name:"Shitty Rust", creator:"p1achu", diff:"unrated", thumb:"thumbnails/rust.png" },
  { id:"shitty-the-golden", name:"Shitty The Golden", creator:"AcropolisBoy", diff:"unrated", thumb:"thumbnails/shitty_thegolden.png" },
  { id:"shitty-time-extreme", name:"Shitty Time Extreme", creator:"polardito", diff:"unrated", thumb:"thumbnails/time_extreme.png" },
  { id:"shitty-kocmoc", name:"Shitty KOCMOC", creator:"zXk15", diff:"unrated", thumb:"thumbnails/shitty_kocmoc.png" },
  { id:"shitty-promethean", name:"Shitty Promethean", creator:"Asbl11", diff:"unrated", thumb:"thumbnails/promethean.png" },
  { id:"after-burner", name:"After Burner", creator:"CryoChemist", diff:"medium", thumb:"thumbnails/afterburner.png" },
  { id:"shitty-sakupen-circles-aakn", name:"Shitty Sakupen Circles", creator:"aakn", diff:"unrated", thumb:"thumbnails/shitty_sakupencircles_harder.png" },
  { id:"bloudeleuste", name:"Bloudeleuste", creator:"MrSpaghetti", diff:"easy", thumb:"https://i.ytimg.com/vi/vgP2RWNg34w/maxresdefault.jpg" },
  { id:"shitty-acheron-nerf", name:"Shitty Acheron nerf", creator:"JOA23", diff:"unrated", thumb:"https://external-preview.redd.it/acheron-76-100-actually-kind-of-fun-for-a-top-1-im-not-v0-Jejj8f-IlAwMzbNBi4igUbWj3b00FtG7Dz47DJ-UKB4.png?width=640&crop=smart&format=pjpg&auto=webp&s=33c0028254718b075fe80d7a56919c7055536358" },
  { id:"shitty-the-plunge", name:"Shitty The Plunge", creator:"krycha31", diff:"unrated", thumb:"thumbnails/the_plunge.png" },
  { id:"sakupen-egg", name:"Sakupen Egg", creator:"Sivlol", diff:"medium", thumb:"https://i.ytimg.com/vi/Wk_LXZegbrE/maxresdefault.jpg" },
  { id:"red-haze-toastlord", name:"Red Haze", creator:"ToastLord", diff:"medium", thumb:"https://i.ytimg.com/vi/K6rmSymCWq0/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLCkTlCQ1C3rWnE3ML_PM5jHitpzqA" },
  { id:"shitty-acropolis", name:"Shitty Acropolis", creator:"AcropolisBoy", diff:"unrated", thumb:"thumbnails/acropolis.png" },
  { id:"cyan", name:"Cyan", creator:"TotoTie", diff:"medium", thumb:"https://i.ytimg.com/vi/Ku_UzE6QNbI/maxresdefault.jpg" },
  { id:"b", name:"B", creator:"Motleyorc", diff:"medium", thumb:"https://i.ytimg.com/vi/vtLGX7XiAUk/maxresdefault.jpg" },
  { id:"amberette", name:"amberette", creator:"spark", diff:"easy", thumb:"https://i.ytimg.com/vi/z6ZefwCcxPs/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLCXjJKAxJL9G0eKVfuze2cR1_pDYw" },
  { id:"bwomp-processing", name:"Bwomp Processing", creator:"EnenzoGD", diff:"easy", thumb:"https://i.ytimg.com/vi/sMwoH8fDySw/maxresdefault.jpg" },
  { id:"red-haze-almondy", name:"Red HazE", creator:"Almondy", diff:"easy", thumb:"https://i.ytimg.com/vi/rk2QK-GQCdE/maxresdefault.jpg" },
  { id:"way-of-the-darkness", name:"Way of the Darkness", creator:"IIINePtunEIII", diff:"medium", thumb:"https://i.ytimg.com/vi/dOJhARl5H30/maxresdefault.jpg" },
  { id:"nautilus", name:"Nautilus", creator:"TheTechniTeam", diff:"easy", thumb:"thumbnails/Nautulis.png" },
  { id:"shitty-quantumprocessing", name:"Shitty Quantum Processing", creator:"D4M5", diff:"unrated", thumb:"thumbnails/quantum_processing.png" },
  { id:"shitty-vsc-2", name:"Shitty VSC 2", creator:"evvGeson", diff:"unrated", thumb:"thumbnails/vsc_hard.png" },
  { id:"the-secret-box-nerf", name:"The Secret Box Nerf", creator:"KingArthur247", diff:"unrated", thumb:"thumbnails/secretbox.png" },
  { id:"zxcircles", name:"ZXCircleS", creator:"Wintter", diff:"easy", thumb:"https://i.ytimg.com/vi/0XVajALPZWw/maxresdefault.jpg" },
  { id:"shitty-zodiac", name:"Shitty Zodiac", creator:"oSpace", diff:"unrated", thumb:"thumbnails/zodiac.png" },
  { id:"shitty-firework-eas", name:"Shitty Firework eas", creator:"MoVavi", diff:"unrated", thumb:"https://i.ytimg.com/vi/juzkIHpy9Sc/maxresdefault.jpg" },
  { id:"bloudebafe", name:"Bloudebafe", creator:"MrSpaghetti", diff:"easy", thumb:"https://i.ytimg.com/vi/mzw12MLY17g/maxresdefault.jpg" },
  { id:"shitty-vsc", name:"Shitty VSC", creator:"enkraxy", diff:"unrated", thumb:"thumbnails/vsc.png" },
  { id:"shitty-aerial-gleam", name:"Shitty Aerial Gleam", creator:"edestus55", diff:"unrated", thumb:"thumbnails/aerial_gleam.png" },
  { id:"shitty-magma-bound", name:"Shitty Magma Bound", creator:"BrookeThe3rd", diff:"unrated", thumb:"thumbnails/magmabound.png" },
  { id:"shitty-nullscapes", name:"Shitty Nullscapes", creator:"ricongd", diff:"unrated", thumb:"thumbnails/nullscapes.png" },
  { id:"shitty-sakupen-circles-leroz", name:"Shitty Sakupen Circles", creator:"LeroZ", diff:"unrated", thumb:"thumbnails/shitty_sakupencircles.png" },
  { id:"ratio-circles", name:"Ratio Circles", creator:"Ch4rlie03", diff:"easy", thumb:"https://i.ytimg.com/vi/-1tTyo08HFI/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLA3V52BwNnNOpleJD7ynRITyaBu0g" },
  { id:"erou", name:"Erou", creator:"JonathanGD", diff:"easy", thumb:"https://i.ytimg.com/vi/_SI8TbLMPy8/maxresdefault.jpg" },
  { id:"toe-2", name:"TOE 2", creator:"RobTop", diff:"easy", thumb:"https://static.wikia.nocookie.net/geometry-dash/images/b/ba/ToE_2.jpg/revision/latest?cb=20160621213450&path-prefix=pl" },
  { id:"past", name:"past", creator:"neigefeu", diff:"easy", thumb:"https://i.ytimg.com/vi/54xF_GApfjA/maxresdefault.jpg" },
  { id:"vogue", name:"VOGUE", creator:"Presta", diff:"easy", thumb:"https://i.ytimg.com/vi/9SPPRk9w4DA/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLCDO9LKJYh5VrW7c5rYwNbOq5xdAA" },
  { id:"living-open", name:"Living Open", creator:"MaFFaKa", diff:"medium", thumb:"https://i.ytimg.com/vi/NKIg8lm48jk/maxresdefault.jpg" },
  { id:"kiln", name:"KILN", creator:"CERUFIFFY", diff:"medium", thumb:"https://i.ytimg.com/vi/NlSiQZLQJ9Y/maxresdefault.jpg" },
  { id:"clubstep", name:"Clubstep", creator:"RobTop", diff:"easy", thumb:"https://i.ytimg.com/vi/hj9A-etWNcQ/maxresdefault.jpg" },
  { id:"deadlocked", name:"Deadlocked", creator:"RobTop", diff:"easy", thumb:"https://s2.dmcdn.net/v/BYwXJ1L_W3RPv1UbP/x720" },
  { id:"deadlocked-dual-x15", name:"Deadlocked Dual x15", creator:"ItsColorsRed16", diff:"unrated", thumb:"https://preview.redd.it/how-do-i-do-deadlocked-dual-wave-v0-x3iecbpfojuc1.jpg?width=1024&format=pjpg&auto=webp&s=62f0918dc3ed95b36a200d88241de1abbd92dc57" },
  { id:"retro-circles", name:"Retro Circles", creator:"Nacho21", diff:"easy", thumb:"https://i.ytimg.com/vi/yVxKTQPzyus/maxresdefault.jpg" },
  { id:"w-a-s-t-e-d", name:"W A S T E D", creator:"Blogde", diff:"easy", thumb:"https://i.ytimg.com/vi/mOULo3jUgXw/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLA1XZlHobm_rtKEl9d1hXbH2WvxJQ" },
  { id:"change-of-scene", name:"Change Of Scene", creator:"Bli", diff:"easy", thumb:"https://i.ytimg.com/vi/alafxkFTprU/maxresdefault.jpg" },
  { id:"vsb-remake", name:"VSB Remake", creator:"bostongamer", diff:"unrated", thumb:"thumbnails/vsb.png" },
  { id:"effervescent", name:"EFFERVESCENT", creator:"friendless", diff:"easy", thumb:"https://i.ytimg.com/vi/1C2lywSsuZE/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLD6-H4aLpdFTUl38q7yYVkAILqbWA" },
  { id:"star-road", name:"Star Road", creator:"Nicki1202", diff:"easy", thumb:"https://i.ytimg.com/vi/a7EzHG8q-tA/maxresdefault.jpg" },
  { id:"gg", name:"GG", creator:"Mulpan", diff:"easy", thumb:"https://i.ytimg.com/vi/atbqdfYbTb8/maxresdefault.jpg" },
  { id:"broken-roulette", name:"Broken Roulette", creator:"NoFlix", diff:"easy", thumb:"https://i.ytimg.com/vi/SYyETT0_3P0/maxresdefault.jpg" },
  { id:"shitty-shardscapes", name:"Shitty Shardscapes", creator:"GDCasanova", diff:"unrated", thumb:"thumbnails/shardscapes.png" },
  { id:"pericolo", name:"Pericolo", creator:"GirlyAle02", diff:"easy", thumb:"https://i.ytimg.com/vi/AFIMMRS2TnQ/maxresdefault.jpg" },
  { id:"blindfolder", name:"Blindfolder", creator:"FeindFighter", diff:"easy", thumb:"https://i.ytimg.com/vi/yg0vN3gAY10/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLAPDWtxDCzMXSXXlMY-SyMR-QPzsg" },
  { id:"memory-reboot", name:"Memory Reboot", creator:"Blogde", diff:"easy", thumb:"https://i.ytimg.com/vi/KqN7o0imsVo/maxresdefault.jpg" },
  { id:"i-made-this-4-fun", name:"I Made this 4 Fun", creator:"Z3R3P", diff:"easy", thumb:"https://i.ytimg.com/vi/OKwPQsssjzQ/maxresdefault.jpg" },
  { id:"eyes-in-the-water", name:"Eyes In The Water", creator:"BowtieGD", diff:"easy", thumb:"https://i.ytimg.com/vi/tySlIt1ZIOM/maxresdefault.jpg" },
  { id:"is", name:"iS", creator:"Grenate", diff:"easy", thumb:"https://i.ytimg.com/vi/KnN3KxeLku4/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLDxk1pSts9rnw30ro7fTkfNCsZPbg" },
  { id:"retrospect", name:"Retrospect", creator:"DangerKat", diff:"easy", thumb:"https://i.ytimg.com/vi/X8EnSWjgeiM/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLCH9FOx193g410L2flEJVoHx4DXbg" },
  { id:"mjko", name:"Mjko", creator:"DangnghiGD", diff:"easy", thumb:"https://i.ytimg.com/vi/8QLxA43IiQ8/maxresdefault.jpg" },
  { id:"high-rebound", name:"High Rebound", creator:"Howler", diff:"easy", thumb:"https://i.ytimg.com/vi/ZZhFcUq3Ndk/maxresdefault.jpg" },
  { id:"shitty-aquamarine-ez", name:"Shitty Aquamarine ez", creator:"ChalnerGD", diff:"unrated", thumb:"https://i.ytimg.com/vi/UBXdd6Y4GJA/sddefault.jpg" },
];

// Historia zmian — najnowsze na górze. Generuje ją admin.html
const CHANGELOG = [
  { date:"2026-09-29", type:"move", id:"shitty-aquamarine-ez", name:"Shitty Aquamarine ez", from:45, to:73 },
  { date:"2026-09-29", type:"move", id:"ratio-circles", name:"Ratio Circles", from:46, to:45, by:"shitty-aquamarine-ez", byName:"Shitty Aquamarine ez", cause:"move" },
  { date:"2026-09-29", type:"move", id:"erou", name:"Erou", from:47, to:46, by:"shitty-aquamarine-ez", byName:"Shitty Aquamarine ez", cause:"move" },
  { date:"2026-09-29", type:"move", id:"toe-2", name:"TOE 2", from:48, to:47, by:"shitty-aquamarine-ez", byName:"Shitty Aquamarine ez", cause:"move" },
  { date:"2026-09-29", type:"move", id:"past", name:"past", from:49, to:48, by:"shitty-aquamarine-ez", byName:"Shitty Aquamarine ez", cause:"move" },
  { date:"2026-09-29", type:"move", id:"vogue", name:"VOGUE", from:50, to:49, by:"shitty-aquamarine-ez", byName:"Shitty Aquamarine ez", cause:"move" },
  { date:"2026-09-29", type:"move", id:"living-open", name:"Living Open", from:51, to:50, by:"shitty-aquamarine-ez", byName:"Shitty Aquamarine ez", cause:"move" },
  { date:"2026-09-29", type:"move", id:"kiln", name:"KILN", from:52, to:51, by:"shitty-aquamarine-ez", byName:"Shitty Aquamarine ez", cause:"move" },
  { date:"2026-09-29", type:"move", id:"clubstep", name:"Clubstep", from:53, to:52, by:"shitty-aquamarine-ez", byName:"Shitty Aquamarine ez", cause:"move" },
  { date:"2026-09-29", type:"move", id:"deadlocked", name:"Deadlocked", from:54, to:53, by:"shitty-aquamarine-ez", byName:"Shitty Aquamarine ez", cause:"move" },
  { date:"2026-09-29", type:"move", id:"deadlocked-dual-x15", name:"Deadlocked Dual x15", from:55, to:54, by:"shitty-aquamarine-ez", byName:"Shitty Aquamarine ez", cause:"move" },
  { date:"2026-09-29", type:"move", id:"retro-circles", name:"Retro Circles", from:56, to:55, by:"shitty-aquamarine-ez", byName:"Shitty Aquamarine ez", cause:"move" },
  { date:"2026-09-29", type:"move", id:"w-a-s-t-e-d", name:"W A S T E D", from:57, to:56, by:"shitty-aquamarine-ez", byName:"Shitty Aquamarine ez", cause:"move" },
  { date:"2026-09-29", type:"move", id:"change-of-scene", name:"Change Of Scene", from:58, to:57, by:"shitty-aquamarine-ez", byName:"Shitty Aquamarine ez", cause:"move" },
  { date:"2026-09-29", type:"move", id:"vsb-remake", name:"VSB Remake", from:59, to:58, by:"shitty-aquamarine-ez", byName:"Shitty Aquamarine ez", cause:"move" },
  { date:"2026-09-29", type:"move", id:"effervescent", name:"EFFERVESCENT", from:60, to:59, by:"shitty-aquamarine-ez", byName:"Shitty Aquamarine ez", cause:"move" },
  { date:"2026-09-29", type:"move", id:"star-road", name:"Star Road", from:61, to:60, by:"shitty-aquamarine-ez", byName:"Shitty Aquamarine ez", cause:"move" },
  { date:"2026-09-29", type:"move", id:"gg", name:"GG", from:62, to:61, by:"shitty-aquamarine-ez", byName:"Shitty Aquamarine ez", cause:"move" },
  { date:"2026-09-29", type:"move", id:"broken-roulette", name:"Broken Roulette", from:63, to:62, by:"shitty-aquamarine-ez", byName:"Shitty Aquamarine ez", cause:"move" },
  { date:"2026-09-29", type:"move", id:"shitty-shardscapes", name:"Shitty Shardscapes", from:64, to:63, by:"shitty-aquamarine-ez", byName:"Shitty Aquamarine ez", cause:"move" },
  { date:"2026-09-29", type:"move", id:"pericolo", name:"Pericolo", from:65, to:64, by:"shitty-aquamarine-ez", byName:"Shitty Aquamarine ez", cause:"move" },
  { date:"2026-09-29", type:"move", id:"blindfolder", name:"Blindfolder", from:66, to:65, by:"shitty-aquamarine-ez", byName:"Shitty Aquamarine ez", cause:"move" },
  { date:"2026-09-29", type:"move", id:"memory-reboot", name:"Memory Reboot", from:67, to:66, by:"shitty-aquamarine-ez", byName:"Shitty Aquamarine ez", cause:"move" },
  { date:"2026-09-29", type:"move", id:"i-made-this-4-fun", name:"I Made this 4 Fun", from:68, to:67, by:"shitty-aquamarine-ez", byName:"Shitty Aquamarine ez", cause:"move" },
  { date:"2026-09-29", type:"move", id:"eyes-in-the-water", name:"Eyes In The Water", from:69, to:68, by:"shitty-aquamarine-ez", byName:"Shitty Aquamarine ez", cause:"move" },
  { date:"2026-09-29", type:"move", id:"is", name:"iS", from:70, to:69, by:"shitty-aquamarine-ez", byName:"Shitty Aquamarine ez", cause:"move" },
  { date:"2026-09-29", type:"move", id:"retrospect", name:"Retrospect", from:71, to:70, by:"shitty-aquamarine-ez", byName:"Shitty Aquamarine ez", cause:"move" },
  { date:"2026-09-29", type:"move", id:"mjko", name:"Mjko", from:72, to:71, by:"shitty-aquamarine-ez", byName:"Shitty Aquamarine ez", cause:"move" },
  { date:"2026-09-29", type:"move", id:"high-rebound", name:"High Rebound", from:73, to:72, by:"shitty-aquamarine-ez", byName:"Shitty Aquamarine ez", cause:"move" },
];

// Progress — poziomy nad którymi teraz pracujesz
const PROGRESS = [
  { name:"Shitty Idols", creator:"Zurteh", best:58, runs:"53–100%", est:"Top 1", thumb:"thumbnails/shitty_idols.png" },
  { name:"Anathema Easy", creator:"ruskysalat", best:17, runs:"31–100%", est:"Top 1", thumb:"thumbnails/anathema.png" },
  { name:"Shitty Amethyst", creator:"hoviajaa", best:71, runs:"43–74%, 52–100%", est:"Top 1", thumb:"thumbnails/amethyst.png" },
  { name:"Shitty Congregation", creator:"AcropolisBoy", best:43, runs:"41–100%", est:"Top 3", thumb:"thumbnails/congregation.png" },
  { name:"Shitty Tidal Wave", creator:"GILD56", best:"60", runs:"38-74, 62-100", est:"Top 1/2", thumb:"thumbnails/Shitty-TidalWave.png" },
];